<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="..\Sos.Commerce.Domain\Sos.Commerce.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Sos.Shared.Kernel\Sos.Shared.Kernel.csproj" />
  </ItemGroup>
</Project>
