<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="..\Sos.Catalog.Application\Sos.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Sos.Shared.Infrastructure\Sos.Shared.Infrastructure.csproj" />
  </ItemGroup>
</Project>
