<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="..\Sos.Catalog.Domain\Sos.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Sos.Shared.Kernel\Sos.Shared.Kernel.csproj" />
  </ItemGroup>
</Project>
