<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="MediatR" />
    <ProjectReference Include="..\Sos.Shared.Kernel\Sos.Shared.Kernel.csproj" />
  </ItemGroup>
</Project>
